project_id = "sufbohhsxlrefkoubmed"

[functions.remix]
verify_jwt = false

[functions.get-track]
verify_jwt = false

[functions.heatmap-sync]
verify_jwt = false

[functions.heatmap-tracks]
verify_jwt = false

[functions.heatmap-track-detail]
verify_jwt = false

[functions.dashboard-music]
verify_jwt = false

[functions.megashuffle-music]
verify_jwt = false

[functions.music-search]
verify_jwt = false

[functions.user-upload]
verify_jwt = false

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-search]
verify_jwt = false

[functions.livekit-token]
verify_jwt = false

[functions.podcast-recording]
verify_jwt = false

[functions.join-voice-room]
verify_jwt = false

[functions.radio-browser]
verify_jwt = false

[functions.podcast-episodes]
verify_jwt = false
